
name: Run tests
on:
  workflow_run:
    workflows: "Check compilation"
    types: [completed]
    branches:
      - 'master'

jobs:
  unit-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker:devel
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Build
        run: make

      - name: Show coverage
        run: make coverage